# Use the spec.group/spec.versions[0].name defined in the XRD
apiVersion: xplane.sijoma.io/v1alpha1
# Use the spec.claimName or spec.name specified in the XRD
kind: RemoteStorage
metadata:
  # Only claims are namespaced, unlike XRs.
  namespace: default
  name: managed-remote-storage
spec:
  # The compositionRef specifies which Composition this XR will use to compose
  # resources when it is created, updated, or deleted.
  compositionRef:
    name: remotestorage-composition

  # Parameters for the Composition to provide the Managed Resources (MR) with
  # to create the actual infrastructure components
    id: "my-id"
    region: "eu-west1"
