apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: remotestorage-composition
spec:
  compositeTypeRef:
    apiVersion: xplane.sijoma.io/v1alpha1
    kind: XRemoteStorage
  mode: Pipeline
  pipeline:
    - step: environmentConfigs
      functionRef:
        name: function-environment-configs
      input:
        apiVersion: environmentconfigs.fn.crossplane.io/v1beta1
        kind: Input
        spec:
          environmentConfigs:
            - type: Reference
              ref:
                name: worker-environment
    - step: patch-and-transform
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: s3-bucket
            base:
              apiVersion: s3.aws.upbound.io/v1beta1
              kind: Bucket
              spec:
                forProvider:
                  forceDestroy: true
                  region: eu-west-1 # <- from env
                  tags:
                    FOO: BAR
                providerConfigRef:
                  name: storage # <- from env
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.region
                toFieldPath: spec.forProvider.region
